[project]
name = 'Tokenized-Blood-Donation-Program'
description = 'A comprehensive smart contract for managing blood donations, NFT rewards, and blood bank inventory management'
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.Tokenized-Blood-Donation-Program]
path = 'contracts/Tokenized-Blood-Donation-Program.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
